name: Kits
author: FinalBoolean, IDurpy, Eths
version: 0.1
main: cf.strafe.Main
commands:
  kit:
    description: Opens the kit gui
    aliases: [kits]
  report:
    description: Reports a player
  discord:
    description: Discord command
  vanish:
    description: Allows staff to go into vanish
    aliases: [v, sv]
  staffchat:
    description: Allows staff to use staff chat
    aliases: [sc]