name: Kits
author: FinalBoolean, IDurpy, Eths
version: 0.1
main: cf.strafe.Main
depend: [WorldGuard]
commands:
  kit:
    description: Opens the kit gui
    aliases: [kits]
  report:
    description: Reports a player
  discord:
    description: Discord command
  vanish:
    description: Allows staff to go into vanish
    aliases: [v, sv]
  staffchat:
    description: Allows staff to use staff chat
    aliases: [sc]
  givelevel:
    description: Allows admins to set levels
    aliases: [gl]
  stats:
    description: Allows the player to see a players stats
  event:
    description: ALlows the player to create events
  sumo:
    description: ALlows staff to create sumo events
  ffa:
    description: Allows staff to create ffa events